### ISSUE TITLE
What is the LavalProject?

### ISSUE THREAD

**Issue by alexandre-mbm** [MaGrosseGit/LavalProject#1]

**Comment by MaGrosseGit** [comment]
Oh that was a long time ago, I used to only work on github then (I didn't know how git worked in general). The Laval project was a little experiment we did witha few friends for a sponsored game jam (called virtual fantasy - limited time) during the Laval Virtual Expo (in a city called Laval as you might have guessed, in France). The point was to make a game in 36 hours with a  theme and a secret object (picked randomly by each team, ours was [this thing](http://mycrazystuff.com/11595-thickbox_default/boule-reservoir-d-eau.jpg)), and preferably to use the sponsors products (which was a Tobii Eyetracker that year). We did not win (ended up fifth I think), but if you are interested here's a little trailer we made for the unfinished project : https://www.youtube.com/watch?v=WwTr74QCV1w
The trailer is in french though, the gist of the story is that you're a god (the god of celebrations) who wants to breath new life into the city with a big party. Your awesome power aloows you to control the flow of the wind while your godly tools (the little water reservoirs mentioned above) allow you to alternatively change the speed of the wind and find hidden objects in the scenes).

P.S : The eyetracker was a pain in the ass to use, we had a faulty unit to begin with (which we managed to fix after a few hours) but the eyetracker was causing crashes on every computer that it was plugged in (for all the teams that were using it). We even got to the point where we couldn't save our unity projects because of the tracker, which sucks when you know your computer can crash any second. All units where pre-release and I don't know if they ever released the product to the public. But the guys representing the brand where not very helpful to say the least. It kinda sucks, the hardware was good, it was mostly the software that was bad (really bad) but that could be fixed.
